### ISSUE TITLE
Albums: support customizable post order

### ISSUE THREAD

**Issue by mfogel** [real-social-media/backend#15]
## Current state

Right now posts in an album are ordered by their `postedAt` datetime, and there's no way to customize that order.

## Desired state

 - default order of posts in an album is order in which they are added to the album
 - frontend can reorder posts in an album
 - customized order is saved on the backend, and whenever the frontend requests the posts in an album they are returned in that order

**Comment by mfogel** [comment]
Planned graphql changes:

```gql
# Edit the order in which a Post appears in an Album
#   - the posts identified by postId and afterPostId must be in the same Album
#   - the post identified by postId will be placed directly after the one
#     identified by afterPostId
#   - if afterPostId is null, postId will be placed at the front
editPostAlbumOrder(postId: ID!, afterPostId: ID): Post
```

**Comment by real-ian** [comment]
@mfogel to be clear, a user can't change his postID to be the id of another user's post, correct?

Thank you ! :)

**Comment by mfogel** [comment]
@real-ian nope, it's more or less impossible to change id's of posts or any other objects. That's not just a restriction of our code - it's from dynamodb. No editing of primary keys in dynamodb.

I will make sure the testsuite for this covers situations where users try to (maliciously) edit other users posts/albums.

**Comment by real-ian** [comment]
@mfogel awesome, please add these tests as a task whenever possible. Thank you! :)
