### ISSUE TITLE
query.self error for new users

### ISSUE THREAD

**Issue by azimgd** [real-social-media/backend#17]
Looks like query.self fails for new users signed up via user pool. Reproduction:

1) Create new user [ok]
2) Confirm new user [ok]
3) Signin with user pool [ok]
4) Get user data from api [fail]

```query```
```
query self {
    self {
      ...userFragment
    }
  }
```

```response```
```
[
  {
    "path": [
      "self"
    ],
    "data": null,
    "errorType": "ClientError",
    "errorInfo": null,
    "locations": [
      {
        "line": 2,
        "column": 3,
        "sourceName": null
      }
    ],
    "message": "User does not exist"
  }
]
```

Sending debug logs privately

**Comment by mfogel** [comment]
One missing step in that list:

1. Create new user [ok]
2. Confirm new user [ok]
3. Signin with user pool [ok]
4. Create user with api. Call either
  - `Mutation.createCognitoOnlyUser`
  - `Mutation.createGoogleUser`
  - `Mutation.createFacebookUser`
5. Get user data from api (`Query.self` or `Query.user`)

Sorry there's so many steps in this list, I blame cognito more than anything :)

**Comment by azimgd** [comment]
Correct. This step was lost after refactor of navigator component, so i missed it as well. Thanks
