### ISSUE TITLE
Video schema doesn't have width/height attributes in response

### ISSUE THREAD

**Issue by azimgd** [real-social-media/backend#243]
While `postType:IMAGE` has an image resolution (width/height) `postType:VIDEO` doesn't return that in response. Do you plan to add support for this in the future or is it best to calculate dimensions on the frontend ? My goal is to have full width video post on home feed.

<img width="471" alt="Screen Shot 2021-06-21 at 18 14 48" src="https://user-images.githubusercontent.com/4882133/122768228-d4c07780-d2bc-11eb-8754-5ab5dcd51621.png">

**Comment by mfogel** [comment]
Addressed in #250 

@azimgd hopefully that PR gives you the info you need via the graphql api. If not let me know, thanks.
